### PR TITLE
change on newbranch

### PR DESCRIPTION
**Pull request by jhsu1623**
Would like to merge README.md of newbranch into README.md of main with the latest updates.  No conflicts

### CODE REVIEW

**Review by jhsu1623 — COMMENTED** [review]
I've reviewed changes and they look OK.  jhsu23

**Review by jhsu1623 — COMMENTED** [review]
reviewed by jhsu23

**Review by ser316asu — APPROVED** [review]
Approve, I did not check things though

**Comment by jhsu1623** [comment]
Closing draft / work in progress

**Review by jhsu1623 — COMMENTED** [review]
Submitting review for 2nd time after canceling work in progress.

**Comment by jhsu1623** [comment]
Reopened after closing and will try to see if I can merge.

**Pull request merged**
